import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

interface DocItem {
  documentId: string;
  originalFileName: string;
  fileType: string;
  uploadedAt?: string;
}

interface BriefQuestionItem {
  number: number;
  question: string;
  clause_reference?: string;
  context: string;
}

interface LawyerBriefResult {
  document_summary: string;
  key_concerns: string[];
  important_clauses: string[];
  questions_for_lawyer: BriefQuestionItem[];
  information_to_bring: string[];
  key_dates: string[];
  unclear_or_missing_information: string[];
  discussion_topics: string[];
  disclaimer: string;
}

export const LawyerPreparation: React.FC = () => {
  const { id: routeDocId } = useParams<{ id: string }>();
  const { getToken } = useAuth();

  const [userDocs, setUserDocs] = useState<DocItem[]>([]);
  const [selectedDocId, setSelectedDocId] = useState<string>(routeDocId || "");
  const [userConcerns, setUserConcerns] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);
  const [fetchingDocs, setFetchingDocs] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [brief, setBrief] = useState<LawyerBriefResult | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  // Load uploaded user documents for dropdown selection
  useEffect(() => {
    const loadDocs = async () => {
      try {
        const token = await getToken();
        if (!token) return;

        const response = await fetch(
          `${import.meta.env.VITE_API_BASE_URL || "http://localhost:8000"}/api/documents`,
          {
            headers: { Authorization: `Bearer ${token}` }
          }
        );

        if (response.ok) {
          const data = await response.json();
          setUserDocs(data.documents || []);
          if (!selectedDocId && data.documents && data.documents.length > 0) {
            setSelectedDocId(data.documents[0].documentId);
          }
        }
      } catch (err) {
        console.error("Failed to load documents:", err);
      } finally {
        setFetchingDocs(false);
      }
    };

    loadDocs();
  }, [getToken, selectedDocId]);

  const handleGenerateBrief = async () => {
    if (!selectedDocId) {
      setError("Please select a document to generate your consultation brief.");
      return;
    }

    if (userConcerns.length > 2000) {
      setError("User concerns must be under 2000 characters.");
      return;
    }

    setLoading(true);
    setError(null);
    setBrief(null);

    try {
      const token = await getToken();
      if (!token) throw new Error("Authentication required.");

      const response = await fetch(
        `${import.meta.env.VITE_API_BASE_URL || "http://localhost:8000"}/api/documents/${selectedDocId}/lawyer-brief`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            user_concerns: userConcerns
          })
        }
      );

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.detail || "Failed to generate lawyer preparation brief.");
      }

      const data = await response.json();
      setBrief(data.result);
    } catch (err: any) {
      setError(err?.message || "An error occurred while generating the brief.");
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyText = () => {
    if (!brief) return;
    const textToCopy = `LEGAL CONSULTATION BRIEF
Generated by LegalLens AI

SUMMARY:
${brief.document_summary}

KEY CONCERNS:
${brief.key_concerns.map((c) => `- ${c}`).join("\n")}

QUESTIONS FOR LEGAL COUNSEL:
${brief.questions_for_lawyer.map((q) => `${q.number}. ${q.question} (${q.clause_reference || 'General'})\n   Context: ${q.context}`).join("\n")}

DOCUMENTS / INFORMATION TO BRING:
${brief.information_to_bring.map((i) => `- ${i}`).join("\n")}

KEY DATES & DEADLINES:
${brief.key_dates.map((d) => `- ${d}`).join("\n")}

UNCLEAR / MISSING INFORMATION:
${brief.unclear_or_missing_information.map((m) => `- ${m}`).join("\n")}

RECOMMENDED DISCUSSION TOPICS:
${brief.discussion_topics.map((t) => `- ${t}`).join("\n")}

LEGAL DISCLAIMER:
${brief.disclaimer}
`;

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const selectedDocObj = userDocs.find((d) => d.documentId === selectedDocId);

  return (
    <div className="min-h-screen bg-background p-6 space-y-6 print:p-0 print:bg-white">
      {/* System Bar (Hidden on print) */}
      <div className="bg-surface-container-high px-6 py-2 rounded-lg flex items-center justify-between text-on-surface-variant font-label-sm text-label-sm border border-outline-variant/30 print:hidden">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-tertiary animate-pulse"></span>
          <span>Lawyer Preparation Briefing System • Active</span>
        </div>
        <div className="font-code-clause text-code-clause">Stitch Screen 10</div>
      </div>

      <div className="max-w-[1520px] mx-auto space-y-6">
        {/* Header Bar (Hidden on print) */}
        <header className="bg-surface-container-lowest p-6 rounded-xl shadow-sm border border-outline-variant/40 flex flex-wrap items-center justify-between gap-4 print:hidden">
          <div>
            <div className="flex items-center gap-2 text-on-surface-variant font-label-sm text-label-sm mb-1">
              <span>Lawyer Preparation</span>
              <span>•</span>
              <span className="text-tertiary font-semibold">Legal Consultation Support</span>
            </div>
            <h1 className="font-headline-md text-headline-md font-bold text-on-surface">
              Legal Consultation Brief Generator
            </h1>
          </div>

          <div className="flex items-center gap-3">
            {brief && (
              <>
                <button
                  onClick={handleCopyText}
                  className="px-4 py-2 bg-surface-container-low hover:bg-surface-container text-on-surface font-label-md text-label-md rounded-lg font-semibold border border-outline-variant/40 flex items-center gap-2"
                >
                  <span className="material-symbols-outlined text-[18px]">
                    {copied ? "check" : "content_copy"}
                  </span>
                  {copied ? "Copied to Clipboard" : "Copy Brief Text"}
                </button>
                <button
                  onClick={handlePrint}
                  className="px-4 py-2 bg-primary-container hover:bg-primary text-on-primary font-label-md text-label-md rounded-lg font-semibold shadow-sm flex items-center gap-2"
                >
                  <span className="material-symbols-outlined text-[18px]">print</span>
                  Export / Save as PDF
                </button>
              </>
            )}
            <Link
              to={selectedDocId ? `/analysis/${selectedDocId}` : "/dashboard"}
              className="px-4 py-2 bg-surface-container-low hover:bg-surface-container text-on-surface font-label-md text-label-md rounded-lg font-semibold border border-outline-variant/40"
            >
              Back to Analysis
            </Link>
          </div>
        </header>

        {/* Configuration Card (Hidden on print) */}
        <div className="bg-surface-container-lowest p-6 rounded-xl shadow-sm border border-outline-variant/40 space-y-4 print:hidden">
          <h3 className="font-label-md text-label-md font-bold text-on-surface uppercase tracking-wide">
            Select Document & Specify Concerns
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
            {/* Document Selection */}
            <div className="md:col-span-5 space-y-2">
              <label className="block font-label-sm text-label-sm font-semibold text-on-surface">
                Analyzed Document
              </label>
              {fetchingDocs ? (
                <p className="font-body-sm text-body-sm text-on-surface-variant">Loading documents...</p>
              ) : userDocs.length === 0 ? (
                <div className="p-3 bg-surface-container-low rounded-lg text-on-surface-variant font-body-sm text-body-sm">
                  No analyzed documents found. Please upload a document first.
                </div>
              ) : (
                <select
                  value={selectedDocId}
                  onChange={(e) => setSelectedDocId(e.target.value)}
                  className="w-full bg-surface-container-low text-on-surface p-3 rounded-lg border border-outline-variant/40 font-body-md text-body-md focus:outline-none"
                >
                  {userDocs.map((doc) => (
                    <option key={doc.documentId} value={doc.documentId}>
                      {doc.originalFileName} ({doc.fileType.toUpperCase()})
                    </option>
                  ))}
                </select>
              )}
            </div>

            {/* Custom User Concerns */}
            <div className="md:col-span-7 space-y-2">
              <div className="flex justify-between items-center">
                <label className="block font-label-sm text-label-sm font-semibold text-on-surface">
                  Your Specific Questions or Concerns (Optional)
                </label>
                <span className="font-label-sm text-[12px] text-on-surface-variant">
                  {userConcerns.length}/2000 chars
                </span>
              </div>
              <textarea
                value={userConcerns}
                onChange={(e) => setUserConcerns(e.target.value.slice(0, 2000))}
                placeholder="e.g. I am worried about the 12-month non-compete clause, or whether pre-existing side projects belong to the company..."
                rows={3}
                className="w-full bg-surface-container-low text-on-surface p-3 rounded-lg border border-outline-variant/40 font-body-md text-body-md resize-none focus:outline-none focus:ring-2 focus:ring-primary"
              ></textarea>
            </div>
          </div>

          {error && (
            <div className="p-3 bg-error-container/60 text-on-error-container rounded-lg font-label-sm text-label-sm border border-error/20">
              {error}
            </div>
          )}

          <button
            onClick={handleGenerateBrief}
            disabled={loading || !selectedDocId}
            className="w-full py-3.5 bg-primary-container hover:bg-primary text-on-primary font-label-md text-label-md rounded-lg shadow-sm font-bold transition-all flex items-center justify-center gap-2 disabled:opacity-50"
          >
            <span className="material-symbols-outlined">description</span>
            {loading ? "Synthesizing Brief for Counsel..." : "Generate Lawyer Consultation Brief"}
          </button>
        </div>

        {/* Loading State */}
        {loading && (
          <div className="bg-surface-container-lowest p-10 rounded-xl shadow-sm border border-outline-variant/40 text-center space-y-3">
            <div className="w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto"></div>
            <h4 className="font-headline-sm text-headline-sm font-bold text-on-surface">
              Synthesizing Consultation Brief...
            </h4>
            <p className="font-body-sm text-body-sm text-on-surface-variant max-w-md mx-auto">
              Transforming document analysis, identified risks, and your custom concerns into an actionable, structured agenda for legal counsel.
            </p>
          </div>
        )}

        {/* Printable Consultation Brief Output */}
        {brief && (
          <div className="bg-surface-container-lowest p-8 rounded-xl shadow-sm border border-outline-variant/40 space-y-8 print:border-none print:shadow-none print:p-0">
            {/* Brief Header Banner */}
            <div className="border-b border-outline-variant/40 pb-6 flex items-start justify-between">
              <div>
                <span className="px-3 py-1 rounded-md bg-tertiary-fixed text-on-tertiary-fixed font-label-sm text-label-sm font-bold uppercase tracking-wider">
                  CONFIDENTIAL LEGAL CONSULTATION BRIEF
                </span>
                <h2 className="font-headline-md text-headline-md font-bold text-on-surface mt-2">
                  Document Consultation Brief
                </h2>
                <p className="font-body-sm text-body-sm text-on-surface-variant mt-1">
                  Document: <strong>{selectedDocObj?.originalFileName || selectedDocId}</strong> • Prepared for Attorney Review
                </p>
              </div>
              <div className="text-right font-label-sm text-label-sm text-on-surface-variant">
                <span>Date: {new Date().toLocaleDateString()}</span>
              </div>
            </div>

            {/* Document Summary */}
            <section className="space-y-2">
              <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface flex items-center gap-2">
                <span className="material-symbols-outlined text-primary text-xl">summarize</span>
                1. Executive Document Summary
              </h3>
              <div className="p-4 rounded-lg bg-surface-container-low border border-outline-variant/30 text-on-surface font-body-md text-body-md leading-relaxed">
                {brief.document_summary}
              </div>
            </section>

            {/* Key Concerns */}
            {brief.key_concerns && brief.key_concerns.length > 0 && (
              <section className="space-y-3">
                <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface flex items-center gap-2">
                  <span className="material-symbols-outlined text-accent-high text-xl">warning</span>
                  2. Priority Concerns for Counsel
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {brief.key_concerns.map((concern, idx) => (
                    <div key={idx} className="p-4 rounded-lg bg-surface-container-low border border-outline-variant/30 flex items-start gap-3">
                      <span className="w-5 h-5 rounded-full bg-accent-high/10 text-accent-high font-label-sm text-label-sm font-bold flex items-center justify-center shrink-0 mt-0.5">
                        !
                      </span>
                      <p className="font-body-sm text-body-sm text-on-surface font-medium">{concern}</p>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* Structured Questions for Lawyer */}
            {brief.questions_for_lawyer && brief.questions_for_lawyer.length > 0 && (
              <section className="space-y-4">
                <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary text-xl">help</span>
                  3. Key Questions to Ask Your Legal Professional
                </h3>
                <div className="space-y-3">
                  {brief.questions_for_lawyer.map((q, idx) => (
                    <div key={idx} className="p-5 rounded-xl bg-surface-container-low border border-outline-variant/30 space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="font-label-md text-label-md font-bold text-primary">
                          Question #{q.number || idx + 1}
                        </span>
                        {q.clause_reference && (
                          <span className="px-2.5 py-0.5 rounded bg-surface-container-high text-on-surface-variant font-code-clause text-code-clause font-semibold">
                            {q.clause_reference}
                          </span>
                        )}
                      </div>
                      <h4 className="font-headline-sm text-headline-sm font-semibold text-on-surface">
                        "{q.question}"
                      </h4>
                      <p className="font-body-sm text-body-sm text-on-surface-variant">
                        <strong>Why this matters:</strong> {q.context}
                      </p>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* Two Column Section: Info to Bring & Key Dates */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Information / Documents to Bring */}
              <section className="space-y-3">
                <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary text-xl">folder_zip</span>
                  4. Documents / Exhibits to Bring
                </h3>
                <ul className="p-4 rounded-lg bg-surface-container-low border border-outline-variant/30 space-y-2">
                  {brief.information_to_bring.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2.5 font-body-sm text-body-sm text-on-surface">
                      <span className="material-symbols-outlined text-[16px] text-primary shrink-0 mt-0.5">check_circle</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </section>

              {/* Key Dates & Milestones */}
              <section className="space-y-3">
                <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary text-xl">event</span>
                  5. Critical Dates & Deadlines
                </h3>
                <ul className="p-4 rounded-lg bg-surface-container-low border border-outline-variant/30 space-y-2">
                  {brief.key_dates.map((dateStr, idx) => (
                    <li key={idx} className="flex items-start gap-2.5 font-body-sm text-body-sm text-on-surface">
                      <span className="material-symbols-outlined text-[16px] text-tertiary shrink-0 mt-0.5">calendar_today</span>
                      <span>{dateStr}</span>
                    </li>
                  ))}
                </ul>
              </section>
            </div>

            {/* Unclear or Missing Information */}
            {brief.unclear_or_missing_information && brief.unclear_or_missing_information.length > 0 && (
              <section className="space-y-3">
                <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface flex items-center gap-2">
                  <span className="material-symbols-outlined text-accent-moderate text-xl">find_in_page</span>
                  6. Omissions & Ambiguous Clauses
                </h3>
                <ul className="p-4 rounded-lg bg-surface-container-low border border-outline-variant/30 space-y-2">
                  {brief.unclear_or_missing_information.map((info, idx) => (
                    <li key={idx} className="flex items-start gap-2.5 font-body-sm text-body-sm text-on-surface">
                      <span className="material-symbols-outlined text-[16px] text-accent-moderate shrink-0 mt-0.5">question_mark</span>
                      <span>{info}</span>
                    </li>
                  ))}
                </ul>
              </section>
            )}

            {/* Discussion Topics */}
            {brief.discussion_topics && brief.discussion_topics.length > 0 && (
              <section className="space-y-3">
                <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary text-xl">chat</span>
                  7. Recommended Consultation Agenda
                </h3>
                <div className="flex flex-wrap gap-2">
                  {brief.discussion_topics.map((topic, idx) => (
                    <span key={idx} className="px-3 py-1.5 rounded-lg bg-surface-container-high text-on-surface font-body-sm text-body-sm font-medium border border-outline-variant/30">
                      • {topic}
                    </span>
                  ))}
                </div>
              </section>
            )}

            {/* Mandatory Disclaimer */}
            <div className="pt-6 border-t border-outline-variant/40">
              <div className="p-4 rounded-xl bg-tertiary-fixed/20 text-on-tertiary-fixed-variant flex items-start space-x-3 border border-tertiary/20">
                <span className="material-symbols-outlined text-tertiary text-xl shrink-0 mt-0.5">gavel</span>
                <p className="font-body-sm text-body-sm leading-relaxed">
                  {brief.disclaimer || "LegalLens AI provides AI-assisted legal information and document preparation support. It does not provide legal advice or replace a qualified legal professional."}
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Mandatory Screen Legal Disclaimer Banner */}
        <footer className="p-4 rounded-xl bg-surface-container-low text-on-surface-variant flex items-start space-x-3 border border-outline-variant/30 print:hidden">
          <span className="material-symbols-outlined text-primary text-xl flex-shrink-0 mt-0.5">shield</span>
          <div className="text-left space-y-1">
            <p className="font-label-sm text-label-sm font-semibold text-on-surface uppercase tracking-wide">
              Analytical Intelligence Guardrail
            </p>
            <p className="font-body-sm text-body-sm text-on-surface-variant leading-relaxed">
              LegalLens AI provides AI-assisted legal information and document preparation support. It does not provide legal advice or replace a qualified legal professional.
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
};
